--트리거
-- C 테이블에 내용 추가하면 LOGTABLE에 시간이랑 '내용추가'라는 내용이 들어간다.
CREATE OR REPLACE TRIGGER TR_DATA_ADD BEFORE INSERT ON C 
FOR EACH ROW 
BEGIN 
IF INSERTING THEN 
INSERT INTO LOGTABLE(CONTENTS) VALUES(:NEW.NAME); 
END IF; 
END TR_DATA_ADD;